############################################################################
# If you give me money, I'll probably put it right back into something else.
# Consider donating to https://metamesh.org or https://codeandsupply.fund.
############################################################################
github: [colindean]
ko_fi: colindean
liberapay: colindean
