AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/fillertext/styles/*.rb'

Gemspec/DateAssignment: 
  Enabled: true

Gemspec/RequireMFA: 
  Enabled: true

Layout/LineEndStringConcatenationIndentation: 
  Enabled: true

Layout/SpaceBeforeBrackets: 
  Enabled: true

Lint/AmbiguousAssignment: 
  Enabled: true

Lint/AmbiguousOperatorPrecedence: 
  Enabled: true

Lint/AmbiguousRange: 
  Enabled: true

Lint/DeprecatedConstants: 
  Enabled: true

Lint/DuplicateBranch: 
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: 
  Enabled: true

Lint/EmptyBlock: 
  Enabled: true

Lint/EmptyClass: 
  Enabled: true

Lint/EmptyInPattern: 
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: 
  Enabled: true

Lint/LambdaWithoutLiteralBlock: 
  Enabled: true

Lint/NoReturnInBeginEndBlocks: 
  Enabled: true

Lint/NumberedParameterAssignment: 
  Enabled: true

Lint/OrAssignmentToConstant: 
  Enabled: true

Lint/RedundantDirGlobSort: 
  Enabled: true

Lint/RequireRelativeSelfPath: 
  Enabled: true

Lint/SymbolConversion: 
  Enabled: true

Lint/ToEnumArguments: 
  Enabled: true

Lint/TripleQuotes: 
  Enabled: true

Lint/UnexpectedBlockArity: 
  Enabled: true

Lint/UnmodifiedReduceAccumulator: 
  Enabled: true

Lint/UselessRuby2Keywords: 
  Enabled: true

Naming/BlockForwarding: 
  Enabled: true

Security/IoMethods: 
  Enabled: true

Style/ArgumentsForwarding: 
  Enabled: true

Style/CollectionCompact: 
  Enabled: true

Style/DocumentDynamicEvalDefinition: 
  Enabled: true

Style/EndlessMethod: 
  Enabled: true

Style/FileRead: 
  Enabled: true

Style/FileWrite: 
  Enabled: true

Style/HashConversion: 
  Enabled: true

Style/HashExcept: 
  Enabled: true

Style/IfWithBooleanLiteralBranches: 
  Enabled: true

Style/InPatternThen: 
  Enabled: true

Style/MapToHash: 
  Enabled: true

Style/MultilineInPatternThen: 
  Enabled: true

Style/NegatedIfElseCondition: 
  Enabled: true

Style/NilLambda: 
  Enabled: true

Style/NumberedParameters: 
  Enabled: true

Style/NumberedParametersLimit: 
  Enabled: true

Style/OpenStructUse: 
  Enabled: true

Style/QuotedSymbols: 
  Enabled: true

Style/RedundantArgument: 
  Enabled: true

Style/RedundantSelfAssignmentBranch: 
  Enabled: true

Style/SelectByRegexp: 
  Enabled: true

Style/StringChars: 
  Enabled: true

Style/SwapValues: 
  Enabled: true

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'lib/fillertext/styles/*.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/*_spec.rb'