language: ruby
rvm:
  - "2.5.1"
  - "2.4.4"
  # EOL on 2.6 release
  - "2.3.7"
  - jruby-9.1.17.0

before_install:
  - gem update --remote bundler
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7
