# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fillertext 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "fillertext".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Colin Dean".freeze]
  s.date = "2021-01-09"
  s.description = "Generates filler text through a direct interface or by monkeypatching Fixnum".freeze
  s.email = "git+gems@cad.cx".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mkd"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mkd",
    "Rakefile",
    "VERSION",
    "fillertext.gemspec",
    "lib/fillertext.rb",
    "lib/fillertext/fillertext.rb",
    "lib/fillertext/fixnum.rb",
    "lib/fillertext/styles/hipster.rb",
    "lib/fillertext/styles/lorem.rb",
    "lib/fillertext/styles/yinzer.rb",
    "spec/fillertext_spec.rb",
    "test/fillertext_test.rb"
  ]
  s.homepage = "http://github.com/colindean/fillertext".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.8".freeze
  s.summary = "Generates filler/placeholder text in a Rubyistic way".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<turn>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<turn>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<turn>.freeze, [">= 0"])
  end
end

