# frozen_string_literal: true

module FillerText
  module Style
    # Style: LoremIpsum
    class LoremIpsum
      def self.text
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas hendrerit condimentum enim, at venenatis nibh pulvinar et. Ut viverra gravida justo at pellentesque. Phasellus tincidunt est a erat feugiat vel dictum quam hendrerit. Mauris turpis augue, imperdiet eu dictum id, laoreet vitae enim. Donec nunc mi, consectetur nec pretium quis, pulvinar et mauris. Integer tristique arcu ut quam mollis tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel mauris mi, id vulputate massa. Cras fermentum, turpis quis elementum dapibus, odio lorem porttitor dui, non eleifend nulla lacus vitae eros. Curabitur eros libero, aliquet quis mollis vitae, rutrum id arcu.
Curabitur vel risus neque, a iaculis nisl. Proin suscipit erat sed enim dignissim tincidunt. Proin vel sapien vel lectus accumsan condimentum. Quisque bibendum sodales orci, sit amet lacinia nulla ornare ac. Duis ac felis porta orci egestas ullamcorper. Nunc ut dolor massa. Suspendisse potenti. Suspendisse et felis ligula. Nullam gravida erat eget sem accumsan convallis. Cras sagittis felis in lorem mattis luctus. Vivamus at blandit leo. Vivamus rhoncus dignissim enim laoreet bibendum. Maecenas in tortor sit amet enim suscipit fringilla. Maecenas venenatis, nisi nec tristique scelerisque, nisl elit eleifend mi, porttitor bibendum mi leo eget nunc.
Morbi pellentesque imperdiet feugiat. Suspendisse consequat, massa commodo scelerisque egestas, metus neque dignissim eros, sit amet semper magna sapien a urna. Vestibulum sed enim lectus, at eleifend massa. Cras lorem orci, interdum ac rutrum non, adipiscing vel lorem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis facilisis elementum ipsum, ut blandit mauris mollis sed. In hac habitasse platea dictumst. Pellentesque elit augue, pharetra sed porttitor iaculis, tincidunt sed mi. Cras consectetur erat a velit laoreet vel hendrerit lectus consequat. Ut risus nisl, bibendum a faucibus ut, hendrerit ut metus. Morbi sodales justo id quam tincidunt et lobortis mi pulvinar. Praesent ac tellus enim. Quisque mi tellus, pellentesque vitae malesuada eget, ullamcorper vel velit. Maecenas imperdiet arcu a eros adipiscing faucibus. Vestibulum vel enim odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Vestibulum pulvinar consectetur laoreet. Nam pharetra massa ac purus luctus molestie. Duis ut sem nisi, at faucibus est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse eu pretium erat. Phasellus condimentum vulputate nulla a euismod. In in urna dapibus metus posuere lobortis sed sit amet massa. Nam libero nulla, ultricies nec blandit sed, accumsan et eros.
Donec sed erat at risus sollicitudin consectetur nec at nulla. Praesent a semper urna. Morbi eu eros ut tellus commodo varius commodo a lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus sed nunc elit, in ornare ipsum. Phasellus et metus ac nibh elementum gravida. Suspendisse dignissim diam sit amet ante aliquam rutrum. Maecenas sit amet eleifend magna.
Pellentesque dictum rhoncus odio, eget hendrerit est egestas fermentum. Mauris nec vulputate felis. Duis luctus felis eu enim semper posuere. Maecenas quis elit metus. Aliquam blandit euismod arcu porta euismod. Sed quis ante vel ante hendrerit sollicitudin. Sed lobortis scelerisque tortor non tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam interdum, elit vitae condimentum sagittis, orci sapien gravida magna, non elementum risus neque eget nisl.
Etiam adipiscing, ante id pharetra pulvinar, dolor tortor dapibus velit, id commodo tellus metus vehicula elit. Maecenas in bibendum eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus pellentesque est vel dolor consectetur et condimentum nulla rhoncus. Vivamus gravida bibendum metus viverra condimentum. Mauris ac purus elit. Suspendisse potenti. Sed eu neque vel ante pellentesque dapibus.
Fusce porttitor egestas est, sit amet mollis nisl dignissim et. Proin rutrum nunc orci, eget eleifend leo. Fusce commodo, tellus eget volutpat euismod, mauris leo luctus arcu, a porttitor lorem turpis a elit. Mauris porta orci at quam aliquam consectetur. Donec lobortis, quam sed rutrum bibendum, urna tellus rutrum erat, et convallis lacus lectus vel elit. Nullam ultricies neque ut dui dapibus eget laoreet sem placerat. Aliquam mi diam, luctus id commodo eu, molestie quis mauris. Nulla sed nulla augue. Fusce id quam eros. Suspendisse mi ante, tempus non sodales ac, commodo at sapien. Ut augue purus, rutrum a posuere a, vestibulum eu risus. Praesent id elit orci, vitae tristique ipsum.
Phasellus eleifend sapien at elit vulputate tincidunt. Praesent quis turpis eros. Proin fermentum elit sit amet augue facilisis at lobortis tortor vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed massa quam, suscipit non aliquam non, commodo ut neque. Etiam sodales porttitor ligula, id varius justo aliquet in. Cras hendrerit, augue non interdum ullamcorper, enim ante pharetra tortor, ac ultrices nulla lacus eget nunc. Curabitur sit amet mauris turpis, vel rhoncus nisi. Nullam venenatis odio vel arcu tincidunt ac pharetra metus dictum. Mauris fringilla nisl sit amet nunc vestibulum sed laoreet sapien porta. Morbi eget mi nec felis egestas tincidunt a eu nisi. Aenean diam ipsum, pretium id cursus nec, vulputate in massa. Sed ut blandit elit. Cras ut arcu neque, fermentum egestas augue. Maecenas ultrices turpis sit amet diam suscipit rutrum. Aliquam iaculis rhoncus ultricies.
Nunc feugiat augue id magna dictum condimentum. Sed vehicula, lorem et molestie ornare, nulla dolor mattis augue, eget vulputate quam massa molestie nisl. Phasellus vestibulum elit sit amet lorem congue ornare. Sed lacinia porta mollis. Pellentesque lacinia accumsan velit, vitae feugiat nibh pharetra eget. Aliquam erat volutpat. Pellentesque dignissim arcu at neque suscipit vel vehicula justo dictum. Suspendisse sit amet imperdiet dui. Fusce egestas pellentesque lorem, vel vestibulum odio vestibulum non.
Maecenas commodo ligula aliquet leo viverra hendrerit. Aliquam erat volutpat. Vestibulum convallis metus in turpis dignissim vitae elementum est blandit. Quisque diam magna, fringilla a tincidunt id, tincidunt ac nunc. In hac habitasse platea dictumst. Pellentesque varius velit ac ligula congue laoreet. Donec rhoncus vehicula dignissim. Nulla feugiat congue pellentesque. Aliquam consequat dapibus ligula vel aliquet. Duis molestie ullamcorper gravida. Morbi tellus magna, ultricies quis vestibulum in, accumsan nec metus. Donec tincidunt condimentum massa, sed viverra neque molestie ac.
Duis congue euismod lacus id posuere. Vestibulum bibendum consectetur nunc. Vestibulum tempus tristique blandit. Suspendisse tincidunt libero neque, eget aliquet tellus. Pellentesque sit amet erat ut odio pellentesque congue. Cras cursus aliquet odio non consectetur. Donec tempor nulla lectus, id hendrerit orci.
Integer leo arcu, tincidunt convallis elementum sit amet, aliquet eu nibh. Sed vitae orci sed justo aliquam laoreet. Aenean feugiat pretium urna ac malesuada. Sed porttitor, arcu ac vulputate feugiat, nulla ipsum eleifend neque, vitae sollicitudin leo purus eu magna. Mauris sit amet ligula nec velit accumsan egestas non id nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris sed nibh eu justo blandit laoreet eget sed risus.
Mauris consectetur, tellus in imperdiet imperdiet, felis sem semper tellus, quis dignissim lectus mi et justo. Nulla condimentum tempor ante, eget ultricies ante convallis a. Quisque eget blandit elit. Praesent ornare purus ut purus viverra molestie. In eget nisl nisl, sit amet consectetur eros. Vestibulum at felis turpis. Nulla eu diam rhoncus risus malesuada dictum quis fringilla tellus. Praesent adipiscing justo in ligula consequat at vulputate diam semper. Donec in lectus vel lorem adipiscing venenatis a sed lacus. Integer venenatis porta luctus. Phasellus at mi augue, quis consequat nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam neque lacus, pulvinar volutpat convallis at, aliquam eget turpis.
Nullam at velit urna. Donec tincidunt ligula vel est fringilla bibendum egestas orci euismod. Donec tempus dolor id lectus porta consectetur. Cras lorem urna, lobortis at sollicitudin eget, interdum eu nisi. Nullam orci ipsum, mattis nec tempus sed, imperdiet non metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam quis justo diam, tincidunt dictum purus. Suspendisse elementum, augue et congue bibendum, lorem dui egestas turpis, interdum mattis mauris massa eu enim. Donec nulla mauris, faucibus sit amet fermentum at, volutpat a risus.
Donec ornare ullamcorper mi, non porttitor est hendrerit ac. Curabitur id turpis a velit tincidunt laoreet. Phasellus consectetur felis sed turpis ullamcorper rhoncus. Donec condimentum justo a orci venenatis sagittis. Aliquam consectetur magna at turpis auctor blandit at sit amet felis. Fusce ac lectus venenatis ante imperdiet fringilla. In quis nisi vitae neque rutrum adipiscing. Nullam dignissim, leo eu bibendum ultrices, dui erat mollis eros, blandit rutrum eros erat at enim. Fusce justo ante, faucibus vehicula semper et, luctus in nulla. Vestibulum mattis ante non diam tempus tempor id non nibh. Maecenas id nisl vitae massa tempor eleifend. Nullam luctus eros vitae lectus porta sodales. Donec vitae nisl dolor. Nulla in tellus at neque consequat ornare. Aliquam varius, ligula ut facilisis pulvinar, dolor ipsum posuere metus, et euismod ligula diam nec sapien. Etiam mollis, odio nec semper condimentum, nulla mauris auctor libero, et volutpat leo quam sit amet diam.
Pellentesque mauris arcu, tincidunt gravida elementum a, sollicitudin in ante. Pellentesque vel tellus quam. Integer consequat turpis ut nisl pharetra id molestie mi porta. Nullam est tellus, faucibus at vehicula ac, eleifend ut erat. Nullam id arcu nunc, quis condimentum urna. Nunc lorem orci, scelerisque et mollis eget, consequat et eros. Cras eu mauris sed felis suscipit gravida. Fusce eu ante neque. Mauris dignissim eleifend augue, id cursus urna facilisis id. Suspendisse consequat lacus in dolor tempor cursus. Maecenas eleifend tortor et nisl congue bibendum. Suspendisse iaculis fringilla nisi at viverra. Proin mi elit, euismod et hendrerit quis, commodo ac orci. Mauris imperdiet, nibh in volutpat suscipit, tortor diam venenatis risus, sed viverra arcu nunc vitae massa. Nunc facilisis erat at orci auctor aliquam.
Maecenas varius consectetur felis, a dictum libero adipiscing et. Pellentesque dapibus, nulla ac pulvinar lobortis, lorem arcu auctor velit, nec iaculis libero augue nec justo. Vestibulum placerat porttitor metus in vulputate. In elementum massa sed risus malesuada pulvinar. Donec in urna eget dui suscipit consequat et sit amet erat. Quisque vel leo eros, sed elementum sem. Sed vehicula tincidunt cursus. Proin interdum, arcu non semper aliquet, ligula felis mattis lacus, ut malesuada nisl nisi ut mi."
      end
    end
  end
end
