name: Dependabot auto-merge
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == github.event.pull_request.head.repo.full_name
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: |
          (
            contains(fromJSON(
              '[
                "rspec-core",
                "sorbet-runtime",
                "minitest",
                "rspec-expectations",
                "rexml",
                "concurrent-ruby",
                "activesupport",
                "bigdecimal",
                "i18n",
                "rspec-mocks",
                "rspec-support",
                "docile"
              ]'),
              steps.metadata.outputs.dependency-names
            )
            && steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            contains(fromJSON(
              '[
                "ruby/setup-ruby"
              ]'),
              steps.metadata.outputs.dependency-names
            )
            && contains(fromJson(
                '["version-update:semver-minor", "version-update:semver-minor"]'),
                steps.metadata.outputs.update-type)
          )
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
