name: Release
on:
  push:
    branches:
    - main
permissions:
  contents: write
  pull-requests: write
jobs:
  fillertext:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: ".github/release-please-config.json"
          manifest-file: ".github/release-please-manifest.json"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          persist-credentials: false
      - name: Get all git tags
        run: git fetch --prune --unshallow --tags
        if: ${{ steps.release.outputs.release_created }}
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: 3.4
        if: ${{ steps.release.outputs.release_created }}
      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}
      - name: publish gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          rake release
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        if: ${{ steps.release.outputs.release_created }}
